default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  template: template0

development:
  <<: *default
  database: kondate_development

test:
  <<: *default
  database: kondate_test
  
production:
  <<: *default
  database: kondate_production
  username: kondate
  password: <%= ENV['KONDATE_DATABASE_PASSWORD'] %>
